### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by xavier83** [haskoin/haskoin#1]
I would like to start hacking and contribute to this project but i can't find any specs for bitcoin protocol? can u give any pointers to any resource. I mean is there an rfc? thanx.

**Comment by jprupp** [comment]
Hello xavier83,

This project is at a very early stage at this point. It consists of both a specification, that we haven't yet started work on, and a Haskell implementation, that we're actively writing at this point, but it's not functional yet. Please participate. This is blank slate. What would you like to work on?

Cheers

**Comment by xavier83** [comment]
I have started reading the source and got it to run successfully under ghc. To my understanding, the current version just connects to the testnet and parses the messages and stores blockchain. I would like to know where is blockchain stored and in what format. I would like to implement code for finding peers or add more peers. I have been reading more about iteratees and enumerator lately.

**Comment by jprupp** [comment]
Hello Xavier,

We're not even storing the blockchain at this point. We've just partially coded the protocol definition. We still even haven't figured out how we're going to go about it all. This is right now at "figuring out how we're going to go about this" stage.

Feel free to code in your tree, and send us push requests for things you add. Beware though that this is a state of flux right now. Things will break badly quite often. It isn't really ready for anything. Consider it just a toy for the moment.

Cheers

**Comment by xavier83** [comment]
I am happy to start early on this project :)

**Comment by jprupp** [comment]
That's great, I wish you good luck.

There are some changes that are being done at this point, especially near the main function. Beware that anything you do at this point will probably not merge cleanly. You probably want to create a separate module to put your peer handling code.

Cheers

**Comment by alaudidaelark** [comment]
Btw, what are the goals of the project? is it just a reference implementation/ to be a feature-rich alternative to other clients?

**Comment by jprupp** [comment]
Hello alaudidaelark,

The goals have somewhat evolved over time. At first it was meant to be a mostly didactic implementation, to accompany the Bitcoin specification that we're meaning to write. Then it became evident that since Haskell allows for very safe code, that is also easy to run in multi-core setups, that we should focus on making it a fully functional (no pun intended) implementation, for actual use.

There hasn't been any talk on how feature-rich the application will be, we're still struggling with the basics here. Neither of us are longtime Haskell programmers, and we're learning as we go. It's still premature for us to think about features.

I wasn't expecting so much attention at this stage, this is kind of cool. Any suggestions on the technical side would be greatly appreciated, especially if anyone happen to have a clear idea about how you'd go about writing this in idiomatic Haskell.

**Comment by jprupp** [comment]
Our primary goals is correctness and cleanliness, expressing the problem in the most sensible manner. No premature optimization shall creep in, especially if such a thing would hurt the expression of the problem at hand. In the true Haskell spirit, we would like to make something that looks and like a clean —albeit complex— mathematical formula.

**Comment by alaudidaelark** [comment]
Any plan to formally verify the implementation? That would be awesome. :P

**Comment by jprupp** [comment]
That sounds like a lot of work for a lazy person like me. :)

**Comment by alaudidaelark** [comment]
Hi, Is there a proper communication channel, where I can reach you guys? irc/email?

**Comment by jprupp** [comment]
Yes, email me to root@xeno-genesis.com.

**Comment by alaudidaelark** [comment]
According to my mail-service , apparently the domain xeno-genesis.com doesn't have mx record. :S

**Comment by jprupp** [comment]
Your mail service isn't working properly, because I have a very nice mx record there.

**Comment by m0dev76** [comment]
Hey guys. I will close this issue for now. Please feel free to contact me by e-mail and I will help you get started with Haskoin.
